theme: jekyll-theme-cayman
# Site settings
title: 马瑞祥 Blog                    
SEOTitle: Lancer的博客 | BY Blog		
description: "Hello World!"	   	  

# SNS settings      
github_username: Lancer     
zhihu_username: Lancer  

# Build settings
# paginate: 10   

# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description: "当你停止尝试时,就是失败的时候"
sidebar-avatar: ruixiang.jpg  
